language: python
    python:
      - "3.6"
    services:
      - postgresql
    env:
      - DJANGO=2.0.1 
      - DB=postgresql
    install:
      - pip install -r requirements.txt
      - pip install coveralls
    before_script:
      - psql -c 'create database test_db;' -U postgres
    script:
      - python manage.py test
      - coverage run --source=manage.py test
    after_success: coveralls