language: python
python:
  - "3.6"
services:
  - postgresql
env:
  - DJANGO=2.1.7
  - DB=postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'create database test_db;' -U postgres
script:
  - cd mentorbot
  - python manage.py test
  - coverage run --source=manage.py test
deploy:
  - provider: heroku
  - api_key:
      secure: "EAAIbZBVFEYxEBANGHJTmNX7Qu1DUAQFqZCq0POq3RHMzFvxXSqdDzsrbqdERwZCJ2RZCke6P6Xpqb9dvc5ZCSTKLd6SFj29Eat9ViSQUSCLM8ZANqCZAMOrlKoPm2cHg6GIXKkQTAX8zU7ZA43c2SsgXUCuqYUj3UQPSeBjP1bh9bAZDZD"
after_success: coveralls
