# Generated by Django 2.0.2 on 2018-07-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=20, unique=True)),
                ('field_details', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ('field_name',),
            },
        ),
    ]
