# Generated by Django 2.0.2 on 2018-07-21 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MentorDetails', '0003_auto_20180721_1600'),
        ('MenteeRequests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedMentorRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_email', models.EmailField(max_length=254)),
                ('requeted_field', models.CharField(max_length=50)),
                ('request_status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menteerequests',
            name='requested_mentorship_field',
        ),
        migrations.AddField(
            model_name='menteerequests',
            name='bio',
            field=models.CharField(default='Mentor me please', max_length=200),
        ),
        migrations.AddField(
            model_name='menteerequests',
            name='email',
            field=models.EmailField(default='jojo@jaja', max_length=70),
        ),
        migrations.AddField(
            model_name='menteerequests',
            name='location',
            field=models.CharField(default='Nairobi', max_length=50),
        ),
        migrations.AddField(
            model_name='menteerequests',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='MentorDetails.MentorProfile'),
        ),
        migrations.AddField(
            model_name='menteerequests',
            name='phone_number',
            field=models.IntegerField(blank=True, default='0709887766'),
        ),
    ]
