# Generated by Django 2.0.2 on 2018-07-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenteeRequests', '0002_auto_20180721_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needmentorrequests',
            old_name='requeted_field',
            new_name='requested_field',
        ),
        migrations.AlterField(
            model_name='menteerequests',
            name='email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='menteerequests',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='needmentorrequests',
            name='requester_email',
            field=models.EmailField(max_length=70),
        ),
    ]
