# Generated by Django 2.0.2 on 2018-07-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MenteeRequests', '0004_auto_20180723_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteerequests',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='MentorDetails.MentorUser'),
        ),
    ]
