# Generated by Django 2.0.2 on 2018-07-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenteeRequests', '0005_auto_20180724_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteerequests',
            name='bio',
            field=models.TextField(default='Mentor me please'),
        ),
        migrations.AlterField(
            model_name='menteerequests',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menteerequests',
            name='location',
            field=models.CharField(default='Nairobi', max_length=150),
        ),
        migrations.AlterField(
            model_name='menteerequests',
            name='mentee_name',
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name='menteerequests',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
