# Generated by Django 2.0.1 on 2018-01-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone_nummber', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('linkdin', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image')),
                ('short_bio', models.TextField()),
                ('mentor_status', models.BooleanField(default=False)),
                ('mentorship_field', models.CharField(max_length=100)),
                ('mentorship_detials', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
