# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('linkdin', models.CharField(max_length=100)),
                ('mentorship_field', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=b'image')),
                ('short_bio', models.TextField()),
                ('mentor_status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
