# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentordetails',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='mentordetails',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mentordetails',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
