# Generated by Django 2.0.2 on 2018-07-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='mentoruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email_address'),
        ),
        migrations.AlterField(
            model_name='mentoruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='mentoruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last_name'),
        ),
    ]
