# Generated by Django 2.0.2 on 2018-07-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorDetails', '0002_auto_20180720_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoruser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mentoruser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='image',
            field=models.FileField(upload_to='.'),
        ),
    ]
