# Generated by Django 2.0.2 on 2018-07-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorDetails', '0003_auto_20180721_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='active',
        ),
        migrations.AddField(
            model_name='mentoruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='mentoruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='image',
            field=models.FileField(upload_to='.../templtes/images/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='mentoruser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
