# Generated by Django 2.0.2 on 2018-07-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MentorDetails', '0006_auto_20180723_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='user',
        ),
    ]
