# Generated by Django 2.0.2 on 2018-07-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorDetails', '0010_auto_20180724_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='avatar',
            field=models.ImageField(default='pic.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
